services:
  music-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    volumes:
      - ./msc:/usr/src/app/dist/msc
    ports:
      - 127.0.0.1:4005:4000
    environment:
      - NODE_ENV=production
      # - DATABASE_URL=postgresql://user:pass@host:port/db?schema=public

